controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    camera_controller: 
      type: forward_command_controller/ForwardCommandController

camera_controller:
  ros__parameters:
    joints:
      - camera_joint
    interface_name: position
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity
